# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CarEnv": "01_environment.ipynb",
         "AgentBase": "02_Agent.ipynb",
         "SimpleNet": "02_Agent.ipynb",
         "SimpleAgent": "02_Agent.ipynb",
         "DuelingNet": "02_Agent.ipynb",
         "RainbowAgent": "02_Agent.ipynb",
         "BridgeBase": "03_Bridge.ipynb",
         "SimpleBridge": "03_Bridge.ipynb",
         "RainbowBridge": "03_Bridge.ipynb",
         "TimeHandler": "04_LoopControl.ipynb",
         "LoopControl": "04_LoopControl.ipynb"}

modules = ["env.py",
           "agent.py",
           "bridge.py",
           "loop.py"]

doc_url = "https://HansjoergW.github.io/bfh_mt_hs2020_rl_basics/"

git_url = "https://github.com/HansjoergW/bfh_mt_hs2020_rl_basics/tree/master/"

def custom_doc_links(name): return None
